# Generated by Django 6.0.3 on 2026-04-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g. Sweeteners).', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from name.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description shown on the category page.')),
                ('image', models.ImageField(blank=True, help_text='Category thumbnail image.', null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Page title shown in search results (max 60 characters).', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Short description shown in search results (max 160 characters).', max_length=160)),
                ('name', models.CharField(help_text='Full product name.', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from name.', max_length=220, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description shown on the detail page.')),
                ('specifications', models.TextField(blank=True, help_text='Technical specs, purity, CAS number, etc. Plain text or simple formatting.')),
                ('image', models.ImageField(blank=True, help_text='Main product image.', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this product from the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The category this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
