# Generated by Django 6.0.3 on 2026-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Application sector (e.g. Bakery, Dairy, Beverages).', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier used in filters.', max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the filter sidebar.')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Certification name (e.g. Halal, Kosher, Non-GMO).', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier used in filters.', max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the filter sidebar.')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_names',
            field=models.CharField(blank=True, help_text='Comma-separated synonyms and trade names (e.g. Ascorbic acid, L-ascorbic acid). Improves search.', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='available_forms',
            field=models.CharField(blank=True, help_text='Physical forms available (e.g. Powder, Granule, Liquid). Comma-separated.', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='cas_number',
            field=models.CharField(blank=True, help_text='CAS Registry Number (e.g. 9000-07-1). Used heavily by B2B buyers.', max_length=50, verbose_name='CAS Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, help_text='Technical data sheet or MSDS (PDF). Displayed as a download on the product page.', null=True, upload_to='datasheets/'),
        ),
        migrations.AddField(
            model_name='product',
            name='e_number',
            field=models.CharField(blank=True, help_text='EU food additive code (e.g. E407). Leave blank if not applicable.', max_length=20, verbose_name='E-Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, choices=[('plant', 'Plant'), ('animal', 'Animal'), ('synthetic', 'Synthetic'), ('mineral', 'Mineral'), ('fermentation', 'Fermentation')], help_text='Source origin — used for Halal/Kosher/Vegan filtering.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Technical specs, purity, viscosity, shelf life, etc.'),
        ),
        migrations.AddField(
            model_name='product',
            name='applications',
            field=models.ManyToManyField(blank=True, help_text='Industry sectors or end-use applications for this product.', to='products.application'),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.ManyToManyField(blank=True, help_text='Quality and compliance certifications this product holds.', to='products.certification'),
        ),
    ]
