# Generated by Django 6.0.3 on 2026-04-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_application_certification_product_alternative_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this product from the website.'),
        ),
    ]
