# Generated by Django 6.0.3 on 2026-04-02 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Page title shown in search results (max 60 characters).', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Short description shown in search results (max 160 characters).', max_length=160)),
                ('title', models.CharField(help_text='News post headline.', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=220, unique=True)),
                ('content', models.TextField(help_text='Full post body. Rich-text editor will be added in the admin phase.')),
                ('featured_image', models.ImageField(blank=True, help_text='Header image for this post.', null=True, upload_to='news/')),
                ('published_date', models.DateField(default=django.utils.timezone.now, help_text='Date shown as the publication date.')),
                ('is_published', models.BooleanField(default=False, help_text='Check to make this post visible on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
