# Generated by Django 6.0.3 on 2026-04-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Full post body. Supports rich text formatting.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Check to make this post visible on the website.'),
        ),
    ]
