# Generated by Django 6.0.3 on 2026-04-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person submitting the inquiry.', max_length=100)),
                ('email', models.EmailField(help_text='Contact email address.', max_length=254)),
                ('company', models.CharField(blank=True, help_text='Company or organisation name (optional).', max_length=150)),
                ('phone', models.CharField(blank=True, help_text='Phone number including country code (optional).', max_length=30)),
                ('subject', models.CharField(help_text='Brief subject of the inquiry.', max_length=200)),
                ('message', models.TextField(help_text='Full inquiry message.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read once the inquiry has been reviewed.')),
                ('product_interest', models.ForeignKey(blank=True, help_text='Product this inquiry relates to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
