# Generated by Django 6.0.3 on 2026-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Bangkok, Thailand', help_text='Office address displayed in the footer and contact page.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps link for the office location. Paste the share URL from Google Maps (e.g. https://maps.google.com/?q=...).', max_length=500),
        ),
    ]
