# Generated by Django 6.0.3 on 2026-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings_address_sitesettings_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL. Leave blank to hide.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL. Leave blank to hide.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='line_url',
            field=models.URLField(blank=True, help_text='LINE Official Account URL or add-friend link. Leave blank to hide.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn company page URL. Leave blank to hide.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL. Leave blank to hide.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='X (Twitter) profile URL. Leave blank to hide.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wechat_id',
            field=models.CharField(blank=True, help_text='WeChat Official Account ID. Leave blank to hide.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='WhatsApp Business link (e.g. https://wa.me/66812345678). Leave blank to hide.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL. Leave blank to hide.', max_length=500),
        ),
    ]
