# Generated by Django 6.0.3 on 2026-05-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL for the map shown on the About page. In Google Maps, click Share → Embed a map → copy only the URL from the src="..." part of the code.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, help_text="Google Maps share link for the 'Get Directions' button (e.g. https://maps.google.com/?q=...). Use the Share → Copy link option in Google Maps.", max_length=500),
        ),
    ]
