# Generated by Django 6.0.3 on 2026-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended size: 1920 × 1080 px (16:9). Use a high-quality photo — it fills the full-width banner.', upload_to='hero/')),
                ('alt_text', models.CharField(blank=True, help_text="Short description of the image for screen readers and SEO (e.g. 'Bulk food-grade citric acid powder').", max_length=150, verbose_name='Alt text')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order. Lower number = shown first. Drag-to-sort is not available — use whole numbers (1, 2, 3).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slide without deleting it.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
    ]
